In [1]:
import pandas as pd
base = pd.read_csv("base_dbs/youtube.csv")
base.head()

,channel_username,channel_id,video_id,video_title,comment_text,comment_id,author,published_at,like_count,reply_count,language,label_sentiment,label_toxicity,label_spam
0,@WWE,UCJ5v_MCY6GNUBTO8-D3XoAg,wj56SBaroCE,Jade Cargill continues to perform knowing the ...,Jade was pushed fast in another company. WWE i...,UgzBqHwpN5Vh2yrBzgx4AaABAg,@IFLDook,2025-06-24T19:52:54Z,2,0,en,positive,toxic,not spam
1,@ZeeTV,UCppHT7SZKKvar4Oc9J4oljQ,3KWNKzs_ptQ,Tum Se Tum Tak - तुम से तुम तक - 7th July Onwa...,Are ye 20 sal mushki se jiye ga tab ladki bewa...,UgwG3UA7RYn2WQG4UqR4AaABAg,@KaynatYasmin-r4l,2025-06-25T18:19:01Z,2,0,so,neutral,toxic,not spam
2,@ColorsTV,UC55IWqFLDH1Xp7iu1_xknRA,eqwlbP4f4G4,Laughter Chefs S2 | Full Episode - 41 | India ...,Aly is fcking rude for no reason its laughter ...,UgylheWfFiDbrcu_GCB4AaABAg,@Geejayy616,2025-06-24T20:18:53Z,0,0,en,neutral,toxic,not spam
3,@김프로KIMPRO,UCiVs2pnGW5mLIc1jS2nxhjg,R_gAdQqH6gA,Perfect Featuring | First Take🎬🤣,Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,UgwFwHS549OChJ8Undd4AaABAg,@FranciscoJavierBritogarcia,2025-06-26T05:34:30Z,0,0,so,neutral,toxic,not spam
4,@ColorsTV,UC55IWqFLDH1Xp7iu1_xknRA,g2pWwrK2fyE,Meri Bhavya Life | Ep. 55 | Uma Requests Risha...,bhavya is furfect maching rishank you don't mi...,UgyzIzjTUfhJAqx-CEh4AaABAg,@ChocoHashi,2025-06-25T04:37:32Z,0,0,en,negative,toxic,not spam

In [7]:
base = base[base["language"] == "en"]
base["year"] = base["published_at"].str.split("-", expand=True)[0].astype(int)
base["text"] = base["comment_text"]
base = base[['text', 'year']]
base["decade"] = (base["year"] // 10) * 10
base["category"] = "youtube comment"
base

,text,year,decade,category
0,Jade was pushed fast in another company. WWE i...,2025,2020,youtube comment
2,Aly is fcking rude for no reason its laughter ...,2025,2020,youtube comment
4,bhavya is furfect maching rishank you don't mi...,2025,2020,youtube comment
7,"He cried, because he knows youre a racist.",2025,2020,youtube comment
8,I love that she licked her!,2025,2020,youtube comment
...,...,...,...,...
44997,Good morning Sir Jai Jagannath 🙏🙏,2025,2020,youtube comment
44998,I'm waiting for the day when it's open for pub...,2025,2020,youtube comment
45000,3:48 bro but Samundar Mai animal \n Ka sound A...,2024,2020,youtube comment
45001,Vot ashley ghatal master plan vot furoley sob ...,2025,2020,youtube comment
45004,We can't imagine her pain 😢,2025,2020,youtube comment

In [ ]:
df = pd.read_parquet("large_dataset.parquet")
df = pd.concat([df, base], ignore_index=True)
df.to_parquet("large_dataset.parquet")
df.head()