https://www.kaggle.com/datasets/rushikeshhiray/textage-dataset

In [4]:
import pandas as pd
temp = pd.read_csv("../.idea/data/base_dbs/textage_large.csv")
temp.head()

,text,category,date,title,author,decade,text_length
0,hEre begynneth the volume intituled and named ...,Book,1473,hEre-begynneth-the-volume-intituled-and-named-...,william-caxton,1470,2890
1,O P A I K L A K In three books The first leaf ...,Book,1473,hEre-begynneth-the-volume-intituled-and-named-...,william-caxton,1470,2940
2,quayersleyda partandin two yere aftyrlabouredn...,Book,1473,hEre-begynneth-the-volume-intituled-and-named-...,william-caxton,1470,3116
3,Iupiter andof the begynnyngandcomyng vp of Tro...,Book,1473,hEre-begynneth-the-volume-intituled-and-named-...,william-caxton,1470,3394
4,comyn w lehe wasrecomandedsolempnly andcalleda...,Book,1473,hEre-begynneth-the-volume-intituled-and-named-...,william-caxton,1470,3338

In [5]:
temp["year"] = temp["date"].astype(int)
temp.drop(['title', 'text_length', 'author', 'date'], axis=1, inplace=True)
temp["language_type"] = "written"
temp.head()

,text,category,decade,year,language_type
0,hEre begynneth the volume intituled and named ...,Book,1470,1473,written
1,O P A I K L A K In three books The first leaf ...,Book,1470,1473,written
2,quayersleyda partandin two yere aftyrlabouredn...,Book,1470,1473,written
3,Iupiter andof the begynnyngandcomyng vp of Tro...,Book,1470,1473,written
4,comyn w lehe wasrecomandedsolempnly andcalleda...,Book,1470,1473,written

In [6]:
import processor
processor.process_db(temp.copy(), "textage_large")

Writing C:\Users\ADMIN\Desktop\code\magshimim_final\processed_dbs\textage_large.parquet
Successfully saved to: C:\Users\ADMIN\Desktop\code\magshimim_final\processed_dbs\textage_large.parquet

,text,category,decade,year,language_type,text_length
0,hEre begynneth the volume intituled and named ...,Book,1470,1473,written,2890
1,O P A I K L A K In three books The first leaf ...,Book,1470,1473,written,2940
2,quayersleyda partandin two yere aftyrlabouredn...,Book,1470,1473,written,3116
3,Iupiter andof the begynnyngandcomyng vp of Tro...,Book,1470,1473,written,3394
4,comyn w lehe wasrecomandedsolempnly andcalleda...,Book,1470,1473,written,3338
...,...,...,...,...,...,...
91723,Yet I was disturbed to learn the facts and hav...,Book,1920,1921,written,2545
91724,do not know whe ther my mother is still alive ...,Book,1920,1921,written,2512
91725,a teacher of the Law Have you forgotten this b...,Book,1920,1921,written,2626
91726,him ask whether someone might be hiding her fr...,Book,1920,1921,written,58
91727,BC THE ECLOGUES by Virgil ECLOGUE I MELIBOEUS ...,Book,1920,1921,written,2665